### ISSUE TITLE
which version of keras-bert is compatible for tensorflow 1.13?

### ISSUE THREAD

**Issue by vikotse** [CyberZHG/keras-bert#215]
I installed keras-bert use `pip install keras-bert`, then installed an incompatible version to tensorflow 1.13.

```
>>> import keras_bert
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qspace/vikoxie/pyenv/miniconda2/lib/python2.7/site-packages/keras_bert/__init__.py", line 1, in <module>
    from .bert import *
  File "/home/qspace/vikoxie/pyenv/miniconda2/lib/python2.7/site-packages/keras_bert/bert.py", line 2, in <module>
    from keras_pos_embd import PositionEmbedding
  File "/home/qspace/vikoxie/pyenv/miniconda2/lib/python2.7/site-packages/keras_pos_embd/__init__.py", line 1, in <module>
    from .pos_embd import PositionEmbedding
  File "/home/qspace/vikoxie/pyenv/miniconda2/lib/python2.7/site-packages/keras_pos_embd/pos_embd.py", line 1, in <module>
    from .backend import keras
  File "/home/qspace/vikoxie/pyenv/miniconda2/lib/python2.7/site-packages/keras_pos_embd/backend.py", line 12, in <module>
    import keras
  File "/home/qspace/vikoxie/pyenv/miniconda2/lib/python2.7/site-packages/keras/__init__.py", line 6, in <module>
    'Keras requires TensorFlow 2.2 or higher. '
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`
```

**Comment by vikotse** [comment]
resolved. version 0.84.0.

**Comment by luleifengzhen** [comment]
Do you mean pip install keras-bert==0.84.0？But I still failed
